### ISSUE TITLE
[ShowPermissions] Show lowest rank colour dot instead of highest.

### ISSUE THREAD

**Issue by vy-storm** [wingio/plugins#10]
How it's set up right now, if I have a blue role which gives me perms W X Y, and a second higher ordered red role that gives me perks W X Y Z, I'll see four red dots next to all my listen perms.

The issue with this is it isn't that helpful for a lot of cases, the highest role you have typically contains all the permissions of the lower ones combined.

What would me much more helpful visually in my mind would be if the colour dot showed the lowest role where that permission is present instead of the highest, this would give a better idea of what significant changes to permissions the higher roles provide.

I'd love a toggle to set things to render this way.

**Comment by wingio** [comment]
unfortunately theres not enough information available to sort by lowest
