### ISSUE TITLE
[Feature Request]show channel permissions 

### ISSUE THREAD

**Issue by Savvy7** [wingio/plugins#19]
[Vendicted asked](https://github.com/Aliucord/plugin-requests/issues/348#issuecomment-951714210)  for it to be requested on your repo instead
> this should be requested as a feature on @wingio's repo

To add another function to ShowPerms (or as a seperate plugin If that's more convenient) , that makes it so that it Shows Permissions for text/voice channels like , Allowed roles , Denied Roles , Denied users
As a new entry in the context menu that shows up when holding down on a channel maybe?

![unknown-2](https://user-images.githubusercontent.com/84286302/138845986-d4264c93-8ae9-4b51-ae5f-e8fadce25162.png)
![unknown-3](https://user-images.githubusercontent.com/84286302/138845994-5d206ad5-66c7-4664-af07-4b80c3d21dcf.png)

**Comment by wingio** [comment]
Added in version 1.4.0
