### ISSUE TITLE
Showperms: When using light mode the permissions boxes show badly.

### ISSUE THREAD

**Issue by HugoNotHere** [wingio/plugins#22]
When using lightmode the permissions boxes don't change to light mode, they have black boxes around them making it hard and user unfriendly to see.
![Screenshot_20211107-194438](https://user-images.githubusercontent.com/80633305/140659532-d7a508a5-d9a8-432f-be41-46f6025da070.jpg)

**Comment by wingio** [comment]
Seems to work fine for me
![Screenshot_20211107-175023.png](https://user-images.githubusercontent.com/44992537/140664806-c2715260-d2c4-486b-ae02-20e68ab7f495.png)
