### ISSUE TITLE
Better Chat Box Goes Over The Phone Screen

### ISSUE THREAD

**Issue by Soft-Bred** [wingio/plugins#23]
It doesn't show in the screenshot, but with phones with curved screens, the chat box is too long on the left side and goes "under" the phones bezels.

![Screenshot_20211120-112119.jpg](https://user-images.githubusercontent.com/60551230/142722961-0ef79509-8976-4596-b5c4-514692ebfc56.jpg)

**Comment by wingio** [comment]
Fixed
