### ISSUE TITLE
(BetterChatbox) See Server Profile

### ISSUE THREAD

**Issue by vy-storm** [wingio/plugins#24]
When in a server, the profile shown upon tapping ones pfp isn't that of the active server (so no roles, server profile edit option, ect).  It would be awesome if it brought up one's server profile instead. Also if the avatar were to change to your server avatar (if different) that would just be icing!

**Comment by wingio** [comment]
it already has both of those features

**Comment by vy-storm** [comment]
> it already has both of those features

After trying again, it does in fact show server avatars now, however it does not show server profile on tap whatsoever at least for me.
v1.2.1

**Comment by vy-storm** [comment]
What I'd expect to see:
![Screenshots_2021-11-24-17-51-22](https://user-images.githubusercontent.com/54405427/143371492-4c0d1d17-1458-4126-80a9-1006708a1e21.png)

What I actually see:
![Screenshots_2021-11-24-17-51-37](https://user-images.githubusercontent.com/54405427/143371544-a7d20636-5936-4511-9267-de98e1280360.png)

**Comment by wingio** [comment]
must be a weird bug only you are experiencing, as i haven't gotten any other reports
