### ISSUE TITLE
(KeywordAlerts) Ability to blacklist certain users and option to disable it when on the same channel.

### ISSUE THREAD

**Issue by WitherredAway** [wingio/plugins#25]
It would be nice to be able to blacklist an user from triggering the keywordalert.

Kind of a seperare suggestion but it would also be nice if there was an option that lets you disable keywordalerts from the same channel you're currently in/viewing

I dont know if either of these are possible, but fingers crossed. Any way, thanks for this awesome plugin :)

**Comment by wingio** [comment]
Your second suggestion has been added

**Comment by WitherredAway** [comment]
That's awesome, thanks! Do you think it would also be possible to block a specific channel?
